import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const Aeonik = localFont({
  src: "./fonts/Aeonik-Regular.woff",
  variable: "--font-aeonik",
  weight: "100 900",
});

const Rubik = localFont({
  src: "./fonts/Rubik.ttf",
  variable: "--font-rubik",
  weight: "100 900",
});
const Eaves = localFont({
  src: "./fonts/Eaves.woff2",
  variable: "--font-eaves",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Aeonik.variable} ${Rubik.variable} ${Eaves.variable} } antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
